/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagoRouteImport } from './routes/pago'
import { Route as OportunidadRouteImport } from './routes/oportunidad'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as DisponibilidadRouteImport } from './routes/disponibilidad'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoberturaParcialRouteImport } from './routes/cobertura.parcial'
import { Route as CoberturaNoCubreRouteImport } from './routes/cobertura.no-cubre'

const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadRoute = OportunidadRouteImport.update({
  id: '/oportunidad',
  path: '/oportunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponibilidadRoute = DisponibilidadRouteImport.update({
  id: '/disponibilidad',
  path: '/disponibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaParcialRoute = CoberturaParcialRouteImport.update({
  id: '/cobertura/parcial',
  path: '/cobertura/parcial',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaNoCubreRoute = CoberturaNoCubreRouteImport.update({
  id: '/cobertura/no-cubre',
  path: '/cobertura/no-cubre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/disponibilidad': typeof DisponibilidadRoute
  '/horarios': typeof HorariosRoute
  '/oportunidad': typeof OportunidadRoute
  '/pago': typeof PagoRoute
  '/cobertura/no-cubre': typeof CoberturaNoCubreRoute
  '/cobertura/parcial': typeof CoberturaParcialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/disponibilidad': typeof DisponibilidadRoute
  '/horarios': typeof HorariosRoute
  '/oportunidad': typeof OportunidadRoute
  '/pago': typeof PagoRoute
  '/cobertura/no-cubre': typeof CoberturaNoCubreRoute
  '/cobertura/parcial': typeof CoberturaParcialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/disponibilidad': typeof DisponibilidadRoute
  '/horarios': typeof HorariosRoute
  '/oportunidad': typeof OportunidadRoute
  '/pago': typeof PagoRoute
  '/cobertura/no-cubre': typeof CoberturaNoCubreRoute
  '/cobertura/parcial': typeof CoberturaParcialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/confirmacion'
    | '/disponibilidad'
    | '/horarios'
    | '/oportunidad'
    | '/pago'
    | '/cobertura/no-cubre'
    | '/cobertura/parcial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confirmacion'
    | '/disponibilidad'
    | '/horarios'
    | '/oportunidad'
    | '/pago'
    | '/cobertura/no-cubre'
    | '/cobertura/parcial'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/confirmacion'
    | '/disponibilidad'
    | '/horarios'
    | '/oportunidad'
    | '/pago'
    | '/cobertura/no-cubre'
    | '/cobertura/parcial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  DisponibilidadRoute: typeof DisponibilidadRoute
  HorariosRoute: typeof HorariosRoute
  OportunidadRoute: typeof OportunidadRoute
  PagoRoute: typeof PagoRoute
  CoberturaNoCubreRoute: typeof CoberturaNoCubreRoute
  CoberturaParcialRoute: typeof CoberturaParcialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidad': {
      id: '/oportunidad'
      path: '/oportunidad'
      fullPath: '/oportunidad'
      preLoaderRoute: typeof OportunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disponibilidad': {
      id: '/disponibilidad'
      path: '/disponibilidad'
      fullPath: '/disponibilidad'
      preLoaderRoute: typeof DisponibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura/parcial': {
      id: '/cobertura/parcial'
      path: '/cobertura/parcial'
      fullPath: '/cobertura/parcial'
      preLoaderRoute: typeof CoberturaParcialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura/no-cubre': {
      id: '/cobertura/no-cubre'
      path: '/cobertura/no-cubre'
      fullPath: '/cobertura/no-cubre'
      preLoaderRoute: typeof CoberturaNoCubreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  DisponibilidadRoute: DisponibilidadRoute,
  HorariosRoute: HorariosRoute,
  OportunidadRoute: OportunidadRoute,
  PagoRoute: PagoRoute,
  CoberturaNoCubreRoute: CoberturaNoCubreRoute,
  CoberturaParcialRoute: CoberturaParcialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
